name = "barokah"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "188.166.212.61:443"
UUID = "7eef712e-292f-4028-9ed1-b4c0fa54a0cc"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
