name = "kontol"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "188.166.241.176"
UUID = "c9d6f5e2-0b40-4ded-b8c9-68500bde4978"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
